version: '3'
services:
  database:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=codewars
  app:
    build:
      context: .
    environment:
      DATABASE_URL: postgres://postgres:codewars@database/postgres
    ports:
      - 9292:9292
